region = 'Region'
culture = 'Culture'
year = 'Year'
desirable_profit = 'DesirableOutcome'
rabbit_classic_queue = 'ClassicReport'
rabbit_reverse_queue = 'ReverseReport'
email = "Email"
stock_price = "Stock price"
planting_price = "Planting price"
prolificy_value = "ProductivityValue"
smtp_mail = "smtptester193@gmail.com"
smtp_pass = "oddn eqnc mrlg kcrs"
